# Generated by Django 3.2.9 on 2021-12-05 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('product_count', models.BigIntegerField(default=0, verbose_name='product_count')),
                ('slug', models.SlugField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryImageModel',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='category-images')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel')),
            ],
            options={
                'verbose_name_plural': 'Category Images',
            },
        ),
    ]
